language: python
dist: xenial
sudo: true
install:
  - sudo apt-get update
  - pip install -r requirements-dev.txt
matrix:
  include:
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
  - name: '3.8'
    python: 3.8
script: tox
after_success: if [ "${TRAVIS_PYTHON_VERSION}" == "3.7" ]; then coveralls; fi;
